Add pronunciation note as a subheader
hpyproject/hpyproject.org pull request #11
Opened 2021-04-03 03:10 UTC by darakian

See https://github.com/hpyproject/hpy/issues/192#issuecomment-812455372
for more

Not super familiar with restructured text, but I believe this adds a subtitle/subheader

2021-04-05 14:17 UTC, hodgestar requested changes
Thank you for making this PR. Currently the text is a sub-section heading -- I think it should just be a new paragraph in this section.

2021-04-05 14:17 UTC, hodgestar commented on pages/index.rst
> +Pronounced /h/ - pie
The `-----` makes a subsection in ReStructured Text. I would recommend just making this sentence a new paragraph after the "HPy provides ..." one below.

2021-04-05 15:49 UTC, darakian commented
> Thank you for making this PR. Currently the text is a sub-section heading -- I think it should just be a new paragraph in this section.

How do you feel about putting it in the `More info` list? I felt like it didn't read well in the sentence just after the main heading.

2021-04-10 11:56 UTC, hodgestar commented
Putting it in "More Info" sounds good. I was wondering what pronunciation notation you were using? Using IPA I would write HPy as `/eɪtʃ-paɪ/` (see http://ipa-reader.xyz/ for how this sounds), but I am a complete pronunciation notation n00b (or `/nu:b/` :).

2021-04-10 18:30 UTC, darakian commented
> Putting it in "More Info" sounds good. 

👍 
> I was wondering what pronunciation notation you were using?

Haha, I'm not using any in particular. Just using the `/h/` to call out h sound. I can swap it over to IPA if you prefer :)

2021-04-10 20:04 UTC, hodgestar commented on pages/index.rst
> +- HPy is pronounced /h/ - pie
```suggestion
- HPy is pronounced */h/ - pie* (or using IPA notation: */eɪtʃ-paɪ/*)
```

2021-04-10 20:05 UTC, hodgestar commented on pages/index.rst
> +- HPy is pronounced */h/ - pie* (or using IPA notation: */eɪtʃ-paɪ/*)
```suggestion
- HPy is pronounced `/h/ - pie` (or using IPA notation: `/eɪtʃ-paɪ/`)
```

2021-04-10 20:07 UTC, hodgestar commented
> Haha, I'm not using any in particular. Just using the `/h/` to call out h sound. I can swap it over to IPA if you prefer :)

Let's have both! I think your simpler version is way more understandable, and we can have IPA for those interested in a rigorous guide. :)

2021-04-10 20:08 UTC, merged